# Archive an already prepared runtime, retaining executable permissions on Unix.
cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED PACKAGE_DIR OR NOT DEFINED ARCHIVE_DIR)
    message(FATAL_ERROR "Pass -DPACKAGE_DIR=... -DARCHIVE_DIR=...")
endif()
get_filename_component(PACKAGE_DIR "${PACKAGE_DIR}" REALPATH)
get_filename_component(parent "${PACKAGE_DIR}" DIRECTORY)
get_filename_component(name "${PACKAGE_DIR}" NAME)
get_filename_component(ARCHIVE_DIR "${ARCHIVE_DIR}" ABSOLUTE)
if(NOT EXISTS "${PACKAGE_DIR}/SHA256SUMS.txt" OR NOT name MATCHES "^ReCraft-[A-Za-z0-9.+-]+-(windows|linux|macos)-x64$")
    message(FATAL_ERROR "Not a prepared ReCraft runtime package: ${PACKAGE_DIR}")
endif()
file(MAKE_DIRECTORY "${ARCHIVE_DIR}")
if(WIN32)
    set(archive "${ARCHIVE_DIR}/${name}.zip")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip -- "${name}"
        WORKING_DIRECTORY "${parent}" RESULT_VARIABLE result)
else()
    set(archive "${ARCHIVE_DIR}/${name}.tar.gz")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${archive}" -- "${name}"
        WORKING_DIRECTORY "${parent}" RESULT_VARIABLE result)
endif()
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Failed to archive ${PACKAGE_DIR}")
endif()
file(SHA256 "${archive}" digest)
get_filename_component(filename "${archive}" NAME)
file(WRITE "${archive}.sha256" "${digest}  ${filename}\n")
message(STATUS "Archive: ${archive} (SHA256 ${digest})")
