# CI-only packaging; explicit allowlist excludes saves, config and reference files.
cmake_minimum_required(VERSION 3.16)
if(POLICY CMP0207)
    cmake_policy(SET CMP0207 NEW)
endif()
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED RUNTIME_DIR OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "Pass -DRUNTIME_DIR=... -DOUTPUT_DIR=...")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/assets" "${OUTPUT_DIR}/licenses")
file(STRINGS "${ROOT}/assets/runtime_assets.txt" runtime_assets)
foreach(asset ${runtime_assets})
    get_filename_component(directory "${asset}" DIRECTORY)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/assets/${directory}")
    configure_file("${RUNTIME_DIR}/assets/${asset}" "${OUTPUT_DIR}/assets/${asset}" COPYONLY)
endforeach()
foreach(document VERSION MICROSOFT_CLIENT_ID README.md)
    configure_file("${ROOT}/${document}" "${OUTPUT_DIR}/${document}" COPYONLY)
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/docs")
foreach(document MICROSOFT_ACCOUNT.md BETA_EVENTS_AND_PROFILE.md)
    configure_file("${ROOT}/docs/${document}" "${OUTPUT_DIR}/docs/${document}" COPYONLY)
endforeach()
configure_file("${ROOT}/docs/ASSET_SOURCES.md" "${OUTPUT_DIR}/licenses/ASSET_SOURCES.md" COPYONLY)
configure_file("${ROOT}/.deps/raylib-1.4.0/LICENSE.md" "${OUTPUT_DIR}/licenses/raylib.md" COPYONLY)
configure_file("${ROOT}/.deps/glfw-3.1.2/COPYING.txt" "${OUTPUT_DIR}/licenses/glfw.txt" COPYONLY)
if(WIN32)
    set(executable "${RUNTIME_DIR}/ReCraft.exe")
    configure_file("${executable}" "${OUTPUT_DIR}/ReCraft.exe" COPYONLY)
    find_program(OBJDUMP_EXECUTABLE objdump REQUIRED)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${OBJDUMP_EXECUTABLE}")
    file(GET_RUNTIME_DEPENDENCIES EXECUTABLES "${executable}"
        DIRECTORIES "${RUNTIME_DLL_DIR}"
        RESOLVED_DEPENDENCIES_VAR dependencies UNRESOLVED_DEPENDENCIES_VAR missing
        PRE_EXCLUDE_REGEXES "api-ms-.*" "ext-ms-.*"
        POST_EXCLUDE_REGEXES ".*[Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\].*")
    if(missing)
        message(FATAL_ERROR "Unresolved runtime DLLs: ${missing}")
    endif()
    foreach(dependency ${dependencies})
        get_filename_component(name "${dependency}" NAME)
        configure_file("${dependency}" "${OUTPUT_DIR}/${name}" COPYONLY)
    endforeach()
elseif(APPLE)
    file(COPY "${RUNTIME_DIR}/ReCraft.app" DESTINATION "${OUTPUT_DIR}")
else()
    file(COPY "${RUNTIME_DIR}/ReCraft" DESTINATION "${OUTPUT_DIR}"
        FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endif()
message(STATUS "Runtime package: ${OUTPUT_DIR}")
