# CI-only packaging; explicit allowlist excludes saves, config and reference files.
cmake_minimum_required(VERSION 3.16)
if(POLICY CMP0207)
    cmake_policy(SET CMP0207 NEW)
endif()
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED RUNTIME_DIR OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "Pass -DRUNTIME_DIR=... -DOUTPUT_DIR=...")
endif()
# A package is a fresh staging directory, never the persistent game directory.
# Refuse stale/user files instead of deleting them or silently publishing them.
get_filename_component(RUNTIME_DIR "${RUNTIME_DIR}" REALPATH)
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
if(OUTPUT_DIR STREQUAL RUNTIME_DIR OR OUTPUT_DIR STREQUAL ROOT)
    message(FATAL_ERROR "OUTPUT_DIR must be a separate, empty staging directory")
endif()
file(GLOB existing "${OUTPUT_DIR}/*" "${OUTPUT_DIR}/.[!.]*" "${OUTPUT_DIR}/..?*")
if(existing)
    message(FATAL_ERROR "Package staging directory is not empty: ${OUTPUT_DIR}. Choose a new OUTPUT_DIR; no files were removed.")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/assets" "${OUTPUT_DIR}/licenses")
file(STRINGS "${ROOT}/assets/runtime_assets.txt" runtime_assets)
foreach(asset ${runtime_assets})
    if(asset MATCHES "(^|/)\\.\\.(/|$)|^/|\\\\|[;\r\n]" OR IS_ABSOLUTE "${asset}")
        message(FATAL_ERROR "Invalid runtime asset path: ${asset}")
    endif()
    get_filename_component(directory "${asset}" DIRECTORY)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/assets/${directory}")
    configure_file("${RUNTIME_DIR}/assets/${asset}" "${OUTPUT_DIR}/assets/${asset}" COPYONLY)
endforeach()
foreach(document VERSION MICROSOFT_CLIENT_ID README.md)
    configure_file("${ROOT}/${document}" "${OUTPUT_DIR}/${document}" COPYONLY)
endforeach()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/docs")
foreach(document MICROSOFT_ACCOUNT.md BETA_EVENTS_AND_PROFILE.md BETA_BLOCKS_022.md BETA_ENTITIES_023.md)
    configure_file("${ROOT}/docs/${document}" "${OUTPUT_DIR}/docs/${document}" COPYONLY)
endforeach()
configure_file("${ROOT}/docs/ASSET_SOURCES.md" "${OUTPUT_DIR}/licenses/ASSET_SOURCES.md" COPYONLY)
configure_file("${ROOT}/.deps/raylib-1.4.0/LICENSE.md" "${OUTPUT_DIR}/licenses/raylib.md" COPYONLY)
configure_file("${ROOT}/.deps/glfw-3.1.2/COPYING.txt" "${OUTPUT_DIR}/licenses/glfw.txt" COPYONLY)
if(WIN32)
    set(executable "${RUNTIME_DIR}/ReCraft.exe")
    configure_file("${executable}" "${OUTPUT_DIR}/ReCraft.exe" COPYONLY)
    find_program(OBJDUMP_EXECUTABLE objdump REQUIRED)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${OBJDUMP_EXECUTABLE}")
    file(GET_RUNTIME_DEPENDENCIES EXECUTABLES "${executable}"
        DIRECTORIES "${RUNTIME_DLL_DIR}"
        RESOLVED_DEPENDENCIES_VAR dependencies UNRESOLVED_DEPENDENCIES_VAR missing
        PRE_EXCLUDE_REGEXES "api-ms-.*" "ext-ms-.*"
        POST_EXCLUDE_REGEXES ".*[Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\].*")
    if(missing)
        message(FATAL_ERROR "Unresolved runtime DLLs: ${missing}")
    endif()
    foreach(dependency ${dependencies})
        get_filename_component(name "${dependency}" NAME)
        configure_file("${dependency}" "${OUTPUT_DIR}/${name}" COPYONLY)
    endforeach()
elseif(APPLE)
    file(MAKE_DIRECTORY "${OUTPUT_DIR}/ReCraft.app/Contents/MacOS")
    configure_file("${RUNTIME_DIR}/ReCraft.app/Contents/Info.plist"
        "${OUTPUT_DIR}/ReCraft.app/Contents/Info.plist" COPYONLY)
    file(COPY "${RUNTIME_DIR}/ReCraft.app/Contents/MacOS/ReCraft"
        DESTINATION "${OUTPUT_DIR}/ReCraft.app/Contents/MacOS"
        FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
else()
    file(COPY "${RUNTIME_DIR}/ReCraft" DESTINATION "${OUTPUT_DIR}"
        FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
endif()
file(READ "${ROOT}/VERSION" version)
string(STRIP "${version}" version)
execute_process(COMMAND git rev-parse HEAD WORKING_DIRECTORY "${ROOT}"
    OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE git_result)
if(NOT git_result EQUAL 0)
    message(FATAL_ERROR "Packaging requires the source Git revision")
endif()
string(TIMESTAMP packaged_utc "%Y-%m-%dT%H:%M:%SZ" UTC)
get_filename_component(package_name "${OUTPUT_DIR}" NAME)
if(package_name MATCHES "-(windows|linux|macos)-x64$")
    set(platform "${CMAKE_MATCH_1}-x64")
else()
    set(platform "${CMAKE_HOST_SYSTEM_NAME}")
endif()
file(WRITE "${OUTPUT_DIR}/BUILD_INFO.txt"
    "version=${version}\nsource_commit=${revision}\nplatform=${platform}\npackaged_utc=${packaged_utc}\n")
file(GLOB_RECURSE package_files LIST_DIRECTORIES false RELATIVE "${OUTPUT_DIR}" "${OUTPUT_DIR}/*")
list(SORT package_files)
set(checksums "")
foreach(path ${package_files})
    file(SHA256 "${OUTPUT_DIR}/${path}" digest)
    string(APPEND checksums "${digest}  ${path}\n")
endforeach()
file(WRITE "${OUTPUT_DIR}/SHA256SUMS.txt" "${checksums}")
message(STATUS "Runtime package: ${OUTPUT_DIR}")
